version: "3.5"

services:
  ####################### Frontend #######################
  frontend:
    stdin_open: true
    tty: true
    restart: on-failure:1
    container_name: inventory-lookup-frontend
    build:
      context: frontend
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
      - frontend-node-cache:/usr/app/node_modules
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
  ####################### API #######################  
  redis: 
    image: redis
    container_name: inventory-lookup-cache
    hostname: redis
    ports:  
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    
  api:
    restart: on-failure:1
    depends_on:  
      - redis
    environment: 
      - REDIS_URL=redis://cache
    container_name: inventory-lookup-api
    build:
      context: api
    env_file: 
      - api/.env
    ports:
      - "4000:4000"
volumes:
  frontend-node-cache:
    name: il-frontend-node-cache
